// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryService.Infrastructure;

#nullable disable

namespace QueryService.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20251211190311_AddCommentTable")]
    partial class AddCommentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueryService.Domain.CommentDomain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVerstion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("QueryService.Domain.PostDomain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("QueryService.Domain.CommentDomain.Comment", b =>
                {
                    b.OwnsOne("QueryService.Domain.CommentDomain.CommentContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("CommentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommentId");

                            b1.ToTable("Comments");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");

                            b1.OwnsOne("Shared.Objects.ModerationResult", "ModerationResult", b2 =>
                                {
                                    b2.Property<Guid>("CommentContentCommentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Hate")
                                        .HasColumnType("int");

                                    b2.Property<int>("SelfHarm")
                                        .HasColumnType("int");

                                    b2.Property<int>("Sexual")
                                        .HasColumnType("int");

                                    b2.Property<int>("Violence")
                                        .HasColumnType("int");

                                    b2.HasKey("CommentContentCommentId");

                                    b2.ToTable("Comments");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentContentCommentId");
                                });

                            b1.Navigation("ModerationResult")
                                .IsRequired();
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("QueryService.Domain.PostDomain.Post", b =>
                {
                    b.OwnsMany("QueryService.Domain.PostDomain.Media", "Media", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("BlobName")
                                .IsRequired();

                            b1.Property<string>("ContainerName")
                                .IsRequired();

                            b1.Property<string>("TranscodedBlobName");

                            b1.Property<int>("Type");

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1.ToJson("Media");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsOne("Shared.Objects.ModerationResult", "ModerationResult", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId");

                                    b2.Property<int>("Media__synthesizedOrdinal");

                                    b2.Property<int>("Hate");

                                    b2.Property<int>("SelfHarm");

                                    b2.Property<int>("Sexual");

                                    b2.Property<int>("Violence");

                                    b2.HasKey("MediaPostId", "Media__synthesizedOrdinal");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "Media__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Shared.Objects.Metadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId");

                                    b2.Property<int>("Media__synthesizedOrdinal");

                                    b2.Property<double>("Duration");

                                    b2.Property<double>("Height");

                                    b2.Property<double>("Width");

                                    b2.HasKey("MediaPostId", "Media__synthesizedOrdinal");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "Media__synthesizedOrdinal");
                                });

                            b1.OwnsMany("Shared.Objects.Thumbnail", "Thumbnails", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId");

                                    b2.Property<int>("Media__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("BlobName")
                                        .IsRequired();

                                    b2.Property<bool>("IsSquare");

                                    b2.Property<double>("Resulation");

                                    b2.HasKey("MediaPostId", "Media__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "Media__synthesizedOrdinal");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();

                            b1.Navigation("ModerationResult");

                            b1.Navigation("Thumbnails");
                        });

                    b.OwnsOne("QueryService.Domain.PostDomain.PostContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsOne("Shared.Objects.ModerationResult", "ModerationResult", b2 =>
                                {
                                    b2.Property<Guid>("PostContentPostId");

                                    b2.Property<int>("Hate");

                                    b2.Property<int>("SelfHarm");

                                    b2.Property<int>("Sexual");

                                    b2.Property<int>("Violence");

                                    b2.HasKey("PostContentPostId");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("PostContentPostId");
                                });

                            b1.Navigation("ModerationResult")
                                .IsRequired();
                        });

                    b.Navigation("Content");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
